---

version: '3'

services:
  app:
    image: scoff1k/devops-for-programmers-project-lvl1:cached
    command: npm test
    env_file: .env.example
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
