---

version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: npm test
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
